# Generated by Django 2.2 on 2020-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'teacher'), (3, 'head_teacher')], null=True),
        ),
    ]
