# Generated by Django 2.2 on 2020-03-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20200310_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultfileupload',
            old_name='exam_type',
            new_name='exam_name',
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='stream',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultfileupload',
            name='file',
            field=models.FileField(null=True, upload_to='result/excel/'),
        ),
    ]
