# Generated by Django 2.2 on 2020-03-14 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_auto_20200314_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
