# Generated by Django 2.2 on 2020-03-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_auto_20200314_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
