# Generated by Django 2.2 on 2020-03-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_auto_20200315_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='results',
            name='exam_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_exam', to='grade.ResultCase'),
        ),
    ]
