# Generated by Django 2.2 on 2020-03-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0008_auto_20200329_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultcase',
            old_name='exam_name',
            new_name='exam_name_cl',
        ),
    ]
