# Generated by Django 2.2 on 2020-03-29 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0009_auto_20200329_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultcase',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
