# Generated by Django 2.2 on 2020-03-29 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0010_resultcase_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultcase',
            name='timed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 20, 10, 45, 660382, tzinfo=utc)),
        ),
    ]
