# Generated by Django 2.2 on 2020-03-29 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0011_resultcase_timed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcase',
            name='timed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
